#!/bin/sh

. ../engine/environment.sh

file="$LIQDB_PROP_FILE"
if [ ! -f "$file" ]
then
  echo "Property file not found. Create new property file from template."
  eval "cp $LIQDB_DEF_PROP_FILE $file"
fi

while IFS=':' read -r key value
do
    eval ${key}=\${value}
done < $file

in=""
echo ""
echo "Enter database url."
echo "Leave free to use stored value: $url"
echo -n "value: "
read in
if [ ! -z "$in" ]; then url=$in
fi

echo "Enter jdbc driver."
echo "Leave free to use stored value: $driver"
echo -n "value: "
read in
if [ ! -z "$in" ]; then driver=$in
fi

echo "Enter jdbc driver file."
echo "Leave free to use stored value: $classpath"
echo -n "value: "
read in
if [ ! -z "$in" ]; then classpath=$in
fi

echo "Enter database username."
echo "Leave free to use stored value: $username"
echo -n "value: "
read in
if [ ! -z "$in" ]; then username=$in
fi

echo "Enter database user password."
echo "Leave free to use stored value: $password"
echo -n "value: "
read in
if [ ! -z "$in" ]; then password=$in
fi

echo ""
echo "Check your configuration"
echo "url : $url"
echo "driver : $driver"
echo "classpath : $classpath"
echo "username : $username"
echo "password : $password"

echo -n "Enter [y] to save: "
read in
if [ ! "$in" = "y" ];
    then echo "exited configuration"
    exit 0
fi

echo "save config"
echo url: $url > $LIQDB_PROP_FILE
echo driver: $driver >> $LIQDB_PROP_FILE
echo classpath: $classpath >> $LIQDB_PROP_FILE
echo username: $username >> $LIQDB_PROP_FILE
echo password: $password >> $LIQDB_PROP_FILE

exit 0